---
- name: installing RPM Fusion
  shell: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

- name: installing utilities
  dnf:
    name:
    - gnome-tweak-tool
    - vlc
    - vim
    - htop
    - jq
    state: present

- name: installing Skype
  shell: rpm -i https://go.skype.com/skypeforlinux-64.rpm

- name: download kubectx and kubens
  get_url:
    url: "{{ item }}"
    dest: /usr/local/bin/
  with_items:
  - https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
  - https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens

- name: setting permissions of kubectx and kubens
  file:
    path: /usr/local/bin/{{ item }}
    mode: "+x"
  with_items:
  - kubectx
  - kubens

- file:
    path: /home/prometherion/.oh-my-zsh/completions
    state: directory

- name: download zsh completsions for kubectx and kubens
  get_url:
    url: "{{ item.url }}"
    dest: /home/prometherion/.oh-my-zsh/completions/{{ item.name }}
  with_items:
  - { url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/kubens.zsh", name: _kubens.zsh }
  - { url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/kubectx.zsh", name: _kubectx.zsh }