---
- name: installing RPM Fusion
  shell: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

- name: adding Kubernetes repo
  copy:
    src: "{{ playbook_dir }}/roles/utility/templates/kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo
    remote_src: yes

- name: installing utilities
  dnf:
    name:
    - gnome-tweak-tool
    - vlc
    - vim
    - htop
    - jq
    - tmux
    - kubectl
    - https://downloads.slack-edge.com/linux_releases/slack-4.1.1-0.1.fc21.x86_64.rpm
    state: present

- name: configuring tmux
  copy:
    src: "{{ playbook_dir }}/roles/utility/templates/.tmux.conf"
    dest: /home/prometherion/.tmux.conf
    remote_src: yes

- name: configuring gitconfig
  copy:
    src: "{{ playbook_dir }}/roles/utility/templates/.gitconfig"
    dest: /home/prometherion/.gitconfig
    remote_src: yes

- name: installing Skype
  yum:
     name: https://go.skype.com/skypeforlinux-64.rpm
     state: present

- name: checking if Helm is installed
  shell: helm
  ignore_errors: yes
  register: helm

- name: installing Helm
  get_url:
    url: https://get.helm.sh/helm-v2.15.2-linux-amd64.tar.gz
    dest: /tmp
  when: helm.rc == 127

- name: unarchiving Helm
  unarchive:
    src: /tmp/helm-v2.15.2-linux-amd64.tar.gz
    dest: /tmp
  when: helm.rc == 127

- name: moving Helm binary
  shell: mv /tmp/linux-amd64/helm /usr/local/bin/helm
  when: helm.rc == 127

- name: download kubectx and kubens
  get_url:
    url: "{{ item }}"
    dest: /usr/local/bin/
  with_items:
  - https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
  - https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens

- name: setting permissions of kubectx and kubens
  file:
    path: /usr/local/bin/{{ item }}
    mode: "+x"
  with_items:
  - kubectx
  - kubens

- file:
    path: /home/prometherion/.oh-my-zsh/completions
    state: directory

- name: download zsh completsions for kubectx and kubens
  get_url:
    url: "{{ item.url }}"
    dest: /home/prometherion/.oh-my-zsh/completions/{{ item.name }}
  with_items:
  - { url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/kubens.zsh", name: _kubens.zsh }
  - { url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/kubectx.zsh", name: _kubectx.zsh }
